[package]
name = "cachetable"
version = "0.1.0"
edition = "2021"

[dependencies]
wyhash2 = "0.2.1"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "access"
harness = false
